# 更新配置文件以反映新的包結構
application:
  name: NovelAI Image Generator
  version: 1.1.0

api:
  url: https://api.novelai.net/ai/generate-image
  timeout: 120
  proxy:
    host: 127.0.0.1
    port: 7890

image:
  width: 832
  height: 1216
  scale: 7.0
  steps: 28
  samples: 1

ui:
  window:
    width: 1024
    height: 768
  theme: system

output:
  directory: output

logging:
  level: INFO
  file: logs/app.log

i18n:
  default_language: en_US

initialization:
  directories:
    - embeds
    - logs
    - output

# 新增生成相關的配置
generation:
  default_model: nai-diffusion-3
  default_action: generate
  max_batch_size: 4

# 包結構調整
package_structure:
  generation: com.zxzinn.novelai.generation
  gui:
    generation: com.zxzinn.novelai.gui.generation
  prompt:
    base: com.zxzinn.novelai.generation.prompt
    embed: com.zxzinn.novelai.generation.prompt.embed